"""`docs/DATA.md` is a licence artifact, and licences do not wait for a cache run.

The provenance doc is generated by `naigos-research`, which needs the raw cache
populated -- so between a change to `ALLOWLIST` and the next full run, the file
in the tree is a statement about the project's obligations that is out of date.
That is tolerable for the "what the data established" half, which is a report on
a measurement. It is not tolerable for the Sources and Attribution tables, which
are the credits a provider's terms require us to display.

So those two sections depend on nothing but the allowlist -- no cache, no
network, no AOI -- and this file asserts the committed file still matches them.
A source added to `ALLOWLIST` with `attribution_required=True` fails here until
`naigos-research --refresh-docs` has been run and the result committed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from naigos.research.allowlist import ALLOWLIST
from naigos.research.run import source_sections

REPO = Path(__file__).resolve().parents[1]
DATA_MD = (REPO / "docs" / "DATA.md").read_text()


@pytest.mark.parametrize("key", sorted(ALLOWLIST))
def test_every_allowlisted_source_is_listed_in_the_provenance_doc(key):
    """The Sources table is the index of everything the project is allowed to
    touch. A source that can be fetched but is not named here is un-provenanced
    data in a repo whose whole claim is that there is none."""
    src = ALLOWLIST[key]
    assert f"| {src.name} | {src.license} |" in DATA_MD


@pytest.mark.parametrize(
    "key", sorted(k for k, s in ALLOWLIST.items() if s.attribution_required)
)
def test_every_source_requiring_attribution_is_credited(key):
    """The obligation is to display the credit, and the doc is where the project
    states it. Missing rows here are the licence breach, not a stale file."""
    src = ALLOWLIST[key]
    assert f"| {src.name} | {src.citation} |" in DATA_MD


def test_the_committed_tables_match_what_the_allowlist_generates_today():
    """The per-source tests above catch an absent source. This one catches an
    edited one: a citation reworded in `ALLOWLIST` and not regenerated, or a row
    hand-patched into `DATA.md` and not put back into the allowlist."""
    assert "\n".join(source_sections()) in DATA_MD, (
        "docs/DATA.md is stale against ALLOWLIST; run `naigos-research --refresh-docs`"
    )


def test_the_sections_generate_without_a_cache_or_a_network():
    """The point of splitting them out. If this ever needs a manifest, the doc
    goes back to being refreshable only by a full run, and the tests above stop
    being enforceable in CI."""
    lines = source_sections()
    assert lines[0] == "## Sources"
    assert "## Cached artifacts" not in lines, "a cache-dependent section leaked in"


def test_the_photorealistic_provider_is_named_as_presentation_only_where_it_is_credited():
    """Crediting Google is necessary but not sufficient. The same doc has to say
    what those pixels are not, or the credit reads as a data provenance row for
    the terrain the detection model consumes."""
    attribution = DATA_MD[DATA_MD.index("## Attribution"):DATA_MD.index("## Cached artifacts")]
    assert "Google" in attribution
    lowered = attribution.lower()
    assert "presentation" in lowered or "not evidence" in lowered
    assert "dem" in lowered
